OBJS=	obj/fem.o \
	obj/vecmat.o \
	obj/bandmat.o \
	obj/assemble.o \
	obj/gaussquad.o \
	obj/shapes1d.o \
	obj/element.o

all: tests.x 

obj/%.o: src/%.c
	gcc -Wall -c $< -o $@

obj/%.o: test/%.c
	gcc -Wall -Isrc -c $< -o $@

tests.x: obj/tests.o $(OBJS)
	gcc -Wall -o $@ $^

test: tests.x
	./tests.x

depend:
	makedepend src/*.c src/*.h

clean:
	rm -f src/*~ obj/* tests.x

# Generated by makedepend
# DO NOT DELETE

src/assemble.o: src/assemble.h src/vecmat.h src/bandmat.h
src/bandmat.o: src/vecmat.h src/bandmat.h
src/element.o: src/shapes1d.h src/gaussquad.h src/assemble.h src/fem.h
src/element.o: src/element.h
src/fem.o: src/assemble.h src/element.h src/bandmat.h src/fem.h
src/gaussquad.o: src/gaussquad.h
src/shapes1d.o: src/shapes1d.h
src/tests.o: src/bandmat.h src/assemble.h src/gaussquad.h src/shapes1d.h
src/tests.o: src/fem.h src/element.h src/vecmat.h
src/vecmat.o: src/vecmat.h
