OBJS=	fem.o \
	vecmat.o \
	bandmat.o \
	assemble.o \
	gaussquad.o \
	shapes1d.o \
	element.o

all: tests.x 

%.o: %.c
	gcc -Wall -c $<

tests.x: tests.o $(OBJS)
	gcc -Wall -o $@ $^

test: tests.x
	./tests.x

depend:
	makedepend *.c *.h

clean:
	rm -f *.o *~ tests.x

# Generated by makedepend
# DO NOT DELETE

assemble.o: assemble.h vecmat.h bandmat.h
bandmat.o: vecmat.h bandmat.h
element.o: shapes1d.h gaussquad.h assemble.h fem.h element.h
fem.o: assemble.h element.h bandmat.h fem.h
gaussquad.o: gaussquad.h
shapes1d.o: shapes1d.h
tests.o: bandmat.h assemble.h gaussquad.h shapes1d.h fem.h element.h vecmat.h
vecmat.o: vecmat.h
